# path to a directory with all packages
storage: ../tmp/local-registry

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m

packages:
  '@botmate/*':
    access: $all
    publish: $all

  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

# log settings
logs:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: true # set offline to true to allow publish offline
