import Providers from '#lib/providers';

import type { Metadata } from 'next';
import getConfig from 'next/config';
import { Poppins } from 'next/font/google';

import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'botmate',
  description: 'Generated by create next app',
};

const config = getConfig();
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers version={config.publicRuntimeConfig.version}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
