name: Docker

on:
  push:
    tags:
      - v*.*.*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: botmate/botmate:${{ github.ref_name }}, botmate/botmate:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            GIT_SHA=${{ github.sha }}
